#' Plot mixture density.
#'
#' Plot the density surface of a mixture.
#'
#' @param mix An object of class \code{\link{normmix_intensity}}.
#' @param win An object of class \code{\link[spatstat]{owin}}.
#' @param L Number of grid on x and y axes.
#' @param truncate Whether the density is truncated in the window (truncate)
#'  or not.
#' @param title1 The title (on top) for the density plot.
#' @param zlims The limits of z axis. The default does not has
#' additional limits on z axis.
#' @param poc The point coodinates for the title. The default is the top middle
#' in the 3-D plot.
#' @param ... Further arguments passed to \code{\link[rgl]{persp3d}}.
#'
#' @export
#' @examples
#' if (require(spatstat)) {
#'   mix1 <- rnormmix(8, .01, 10, square(2), rand_m = TRUE)
#'   plot(mix1, 100, square(2))
#' }
plot.normmix_intensity <- function(mix, win, L = 100,
                         title1="Poisson Process Intensity", truncate = TRUE,
                         zlims = c(0, 0),
                         pos=c(0,0,0), grayscale = FALSE, ...) {
  xcoord <- seq(win$xrange[1], win$xrange[2], length.out = L)
  ycoord <- seq(win$yrange[1], win$yrange[2], length.out = L)

  xlims <- c(win$xrange)
  ylims <- c(win$yrange)

  z <- mix$lambda*dnormmix(mix, win = win, xcoord, ycoord, truncate = truncate)$v

  jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                                   "#7FFF7F", "yellow", "#FF7F00", "red",
                                   "#7F0000"))
  if (grayscale == TRUE) {
    col <- gray.colors(100)[findInterval(t(z), seq(min(z), max(z), length = 100))]
  } else {
    col <- jet.colors(100)[findInterval(t(z), seq(min(z), max(z), length = 100))]
  }

  if (zlims[1] == 0 && zlims[2] == 0) {
    zlims=c(0,max(z))
  }

  if (.Platform$OS.type == "unix") {
    rgl::layout3d(matrix(1:2, 1, 2), widths = c(5, 1))
  }
  rgl::open3d(windowRect = c(0, 45, 612, 657), zoom=1.2)
  U=rgl::par3d("userMatrix")
  rgl::par3d(userMatrix=
               rgl::rotate3d(U,pi/4,0,0,1))

  rgl::persp3d(x = xcoord, y = ycoord, z = t(z),
               color = col, xlab="x",ylab="y",zlab="",
               zlim=c(zlims[1]-0.01,zlims[2]),
               box = FALSE, axes = FALSE)
  rgl::axis3d('x')
  rgl::axis3d('y')
  rgl::axis3d('z-+', pos = c(xlims[1], ylims[2], 0))
  rgl::title3d(main = NULL)
  rgl::text3d(xlims[2], ylims[2], zlims[2], texts = title1)

  if (grayscale == TRUE) {
    rgl::bgplot3d(suppressWarnings(
      fields::image.plot(legend.only = TRUE,
#                         smallplot= c(.8,.82,0.05,.7),
                         zlim = zlims,
                         col = gray.colors(100))))
  } else {
    rgl::bgplot3d(suppressWarnings(
      fields::image.plot(legend.only = TRUE,
#                         smallplot= c(.8,.82,0.05,.7),
                         zlim = zlims,
                         col = jet.colors(100))))

  }
}


#' Plot spatial point pattern generated from mixture.
#'
#' Plot funciton for spatial point pattern generated from mixture. It's an
#' alternative to spatstat's plotting functions.
#'
#' @param spp A point pattern of class sppmix or \code{\link[spatstat]{ppp}}.
#' @param ... Parameters passed to \code{\link[ggplot2]{ggplot}}.
#'
#' @import ggplot2
#' @export
#' @examples
#' # plot point patterns generated by sppmix
#' mix1 <- rnormmix(3, .01, 5, square(1))
#' spp <- rsppmix(100, mix1, square(1))
#' plot(spp)
#'
#' # plot point patterns generated by spatstat
#' spp <- spatstat::rpoispp(100)
#' plot.spp(spp)
plot.sppmix <- function(spp, ...) {
  df <- as.data.frame(spp)
  p <- ggplot2::ggplot(df, aes(x, y), ...) +
    ggplot2::labs(x = "X", y = "Y",
                  title = paste("Spatial Point Pattern with",
                                nrow(df), "Points")) +
    ggplot2::theme_classic() +
    ggplot2::coord_cartesian(xlim = spp$window$xrange, ylim = spp$window$yrange)
  p + ggplot2::geom_point()
}

#' Plot contour for intensity surface
#'
#' Create a contour plot for the intensity surface with or without realizations
#' on it.
#'
#' @param mix Object of class \code{\link{normmix_intensity}}.
#' @param pattern Object of class \code{\link{ppp}}
#' @param win Object of class \code{\link{owin}}
#' @param L number of grids on each coordinate.  The default is L=100.
#' @param title title for the contour plot.
#' @param points Logical flag indicating whether plot realizations, i.e.
#' locations, with the contour plot. The default is TRUE.
#' @param filled Logical flag indicating whether plot filled contour plot.
#' The default is TRUE.
#' @param truncate Logical flag indicating whether truncation is used for
#'  \code{pattern}. The default is TRUE.
#' @param ... Further arguments passed to \code{\link[rgl]{filled.contour}}.
#'
#' @examples
#' # generate a mixture with given ps, mus and sigmas
#' mix1 <- normmix(ps=c(.5, .5),
#'                 mus=list(c(.2, .2), c(.7, .7)),
#'                 sigmas=list(.01*diag(2), .02*diag(2)))
#' # generate a realization from mixture mix1
#' pp1 <- rsppmix(200, mix1, spatstat::square(1))
#' # plot the theoretical intensity surface with a realization
#' plot_contour(mix1,pp1,spatstat::square(1))
#' @export
plot_contour <- function(mix, pattern, win = Window(pattern), L = 100,
                         title="Mixture intensity with",
                         points = TRUE, filled = TRUE, truncate = TRUE, ...) {
  xcoord <- seq(win$xrange[1], win$xrange[2], length.out = L)
  ycoord <- seq(win$yrange[1], win$yrange[2], length.out = L)

  surf <- dnormmix(mix, win = win, xcoord, ycoord, truncate = truncate)
  z <- mix$lambda*surf$v
  grid <- expand.grid(xcoord,ycoord)
  temp <- data.frame(grid$Var1,grid$Var2,as.vector(t(z)))
  names(temp) <- c("x","y","z")

  # assign colors to heights for each point
  jet.colors <- grDevices::colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                                              "#7FFF7F", "yellow", "#FF7F00", "red",
                                              "#7F0000"))
  #col <- jet.colors(1000)[findInterval(z$v, seq(min(z$v), max(z$v), length = 1000))]

  #plot(z, col = col)
  if (filled == TRUE){
    if (points == TRUE){
      title1 <- list(
        bquote(paste(lambda,"=",.(mix$lambda),", n=",.(pattern$n))),
        title
      )
      filled.contour(x=xcoord,y=ycoord, z=t(z),color = jet.colors,
                       plot.axes = { axis(1);
                         axis(2);
                         points(pattern$x, pattern$y, pch = 20)},
                       frame.plot = FALSE, asp = 1, axes = TRUE, ... )
      mtext(do.call(expression, title1), side = 3, line = 0:1, at = 0.35)
    } else {

      filled.contour(x=xcoord,y=ycoord, z=t(z),
                     color = jet.colors, plot.title = title(main = title),
                     frame.plot = FALSE, asp = 1,axes = TRUE, ...)
    }
  } else {

    m <- ggplot2::ggplot(temp,aes(x, y, z = z)) +
      ggplot2::labs(x = "X", y = "Y",
                    title = paste("Contour of the intensity surface with",
                                  pattern$n, "Points")) +
      ggplot2::stat_contour(aes(colour = ..level..))
    if (points) m <- m + geom_point(data=as.data.frame(pattern),aes(x, y, z=0))
    return(m)
  }
}

