#' Plot MCMC chains for mus and ps
#'
#' Plot MCMC chains generated by \code{\link{est_mix_damcmc}}
#' @inheritParams plot_avgsurf
#' @author Athanasios Christou Micheas, Jiaxun Chen, Yuchen Wang
#' @export
#' @examples
#' # generate data
#' mix2 <- normmix(ps=c(.4, .6), mus=list(c(0.1, 0.1), c(0.8, 0.8)),
#' sigmas=list(.02*diag(2), .01*diag(2)))
#' pp2 <- rsppmix(100,mix2,square(1))
#' # Run Data augmentation MCMC and get posterior realizations
#' post=est_mix_damcmc(pp2,L = 5000,2,truncate = F)
#' # plot MCMC chains for parameter mus and ps
#' plot_chains(post)

plot_chains<- function(fit, burnin = length(fit$allgens_List) / 10) {
    L=length(fit$allgens_List)
    genps = fit$genps[(burnin + 1):L, ]
    genmus = fit$genmus[, , (burnin + 1):L]
    m = dim(fit$genmus)[1]
  plot(genps[,1], xlab = "Iteration", ylab = "p",
       type = "l",main =
         "Generated mixture probabilities\nComponent 1")
  for (i in 2:m) {
    plot(genps[,i], xlab = "Iteration", ylab = "p",
         type = "l",main =
           paste("Generated mixture probabilities\nComponent",i))
  }

  plot(genmus[1,1,],xlab = "Iteration",ylab = bquote(mu),
       type = "l", main =
         "Generated mixture means\nComponent 1, x-coord")
  plot(genmus[1,2,], xlab = "Iteration", ylab =bquote(mu),
       type = "l",main =
         "Generated mixture means\nComponent 1, y-coord")

  for (i in 2:m) {
    plot(genmus[i,1,], xlab = "Iteration", ylab = bquote(mu),
         type = "l", main =
           paste("Generated mixture means\nComponent"
                 ,i,", x-coord"))
    plot(genmus[i,2,], xlab = "Iteration", ylab =
           bquote(mu), type = "l", main =
           paste("Generated mixture means\nComponent"
                 ,i,", y-coord"))
  }

}
