#' Plot mixture density.
#'
#' Plot the density surface of a mixture.
#'
#' @param mix An object of class \code{\link{normmix}}.
#' @param win An object of class \code{\link[spatstat]{owin}}.
#' @param L Length of grid on x and y axes.
#' @param truncate Whether the density is truncated in the window (truncate)
#'  or not.
#' @param ... Further arguments passed to \code{\link[rgl]{persp3d}}.
#' @export
#' @examples
#' if (require(spatstat)) {
#'   mix1 <- rnormmix(8, .01, 10, square(2), rand_m = T)
#'   plot(mix1, square(2))
#' }
plot.normmix <- function(mix, win, L = 100, truncate = TRUE, ...) {
  xcoord <- seq(win$xrange[1], win$xrange[2], length.out = L)
  ycoord <- seq(win$yrange[1], win$yrange[2], length.out = L)

  z <- dnormmix(mix, win = win, xcoord, ycoord, truncate = truncate)$v


  # assign colors to heights for each point
  jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                                   "#7FFF7F", "yellow", "#FF7F00", "red",
                                   "#7F0000"))
  col <- jet.colors(100)[findInterval(z, seq(min(z), max(z), length = 100))]

  rgl::open3d()
  rgl::persp3d(x = xcoord, y = ycoord, z = z,
               color = col, alpha = .8, ...)
}


#' Plot spatial point pattern generated from mixture.
#'
#' Plot funciton for spatial point pattern generated from mixture. It's an
#' alternative to spatstat's plotting functions.
#'
#' @param spp A point pattern of class sppmix or \code{\link[spatstat]{ppp}}.
#' @param ... Parameters passed to \code{\link[ggplot2]{ggplot}}.
#'
#' @importFrom ggplot2 ggplot aes xlim ylim labs geom_point
#' @export
#' @examples
#' # plot point patterns generated by sppmix
#' mix1 <- rnormmix(3, .01, 5, square(1))
#' spp <- rsppmix(100, mix1, square(1))
#' plot(spp)
#'
#' # plot point patterns generated by spatstat
#' spp <- spatstat::rpoispp(100)
#' plot.spp(spp)
plot.sppmix <- function(spp, ...) {
  df <- as.data.frame(spp)
  p <- ggplot(df, aes(x, y), ...) +
    xlim(spp$window$xrange) + ylim(spp$window$yrange) +
    labs(x = "X", y = "Y",
         title = paste("Spatial Point Pattern with", nrow(df), "Points"))
  p + geom_point()
}

#' @export
plot.dares <- function(dares) {
  plot.ts(dares$ps)
}

#' @export
plot_contour <- function(mix, points = TRUE, pattern, win, L = 100,
                                  truncate = TRUE, ...) {
  xcoord <- seq(win$xrange[1], win$xrange[2], length.out = L)
  ycoord <- seq(win$yrange[1], win$yrange[2], length.out = L)

  z <- dnormmix(mix, win = win, xcoord, ycoord, truncate = truncate)$v

  # assign colors to heights for each point
  jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                                   "#7FFF7F", "yellow", "#FF7F00", "red",
                                   "#7F0000"))
  #col <- jet.colors(1000)[findInterval(z$v, seq(min(z$v), max(z$v), length = 1000))]

  #plot(z, col = col)
  if (points == TRUE){
    filled.contour(x=xcoord,y=ycoord, z=t(z),color = jet.colors,
                   plot.axes = { axis(1); axis(2);
                  points(pattern$x, pattern$y,pch = 16) },
                  frame.plot = FALSE,asp = 1 ,axes = TRUE, ... )
  } else {
    filled.contour(x=xcoord,y=ycoord, z=t(z),
                   color = jet.colors,
                   frame.plot = FALSE, asp = 1,axes = TRUE, ...)
  }
}
