# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ApproxAvgPostIntensity <- function(genmix, lamdas, LL, burnin, xlims, ylims) {
    .Call('sppmix_ApproxAvgPostIntensity', PACKAGE = 'sppmix', genmix, lamdas, LL, burnin, xlims, ylims)
}

#' @export
ApproxCompMass_sppmix <- function(L, xlims, ylims, mu, sig, siginv) {
    .Call('sppmix_ApproxCompMass_sppmix', PACKAGE = 'sppmix', L, xlims, ylims, mu, sig, siginv)
}

#' @export
ApproxMHRatiomu_sppmix <- function(L, xlims, ylims, curmu, propmu, sig, siginv) {
    .Call('sppmix_ApproxMHRatiomu_sppmix', PACKAGE = 'sppmix', L, xlims, ylims, curmu, propmu, sig, siginv)
}

#' @export
ApproxMHRatiosig_sppmix <- function(L, xlims, ylims, mu1, propsigma, sig, siginv) {
    .Call('sppmix_ApproxMHRatiosig_sppmix', PACKAGE = 'sppmix', L, xlims, ylims, mu1, propsigma, sig, siginv)
}

#' @export
ApproxBayesianModelAvgIntensity_sppmix <- function(genBDmix, lamdas, numcomp, distr_numcomp, mincomp, maxcomp, LL, xlims, ylims) {
    .Call('sppmix_ApproxBayesianModelAvgIntensity_sppmix', PACKAGE = 'sppmix', genBDmix, lamdas, numcomp, distr_numcomp, mincomp, maxcomp, LL, xlims, ylims)
}

#' @export
BDMCMC2d_sppmix <- function(maxnumcomp, data, xlims, ylims, L, LL, truncate, lamda, lamdab, hyper) {
    .Call('sppmix_BDMCMC2d_sppmix', PACKAGE = 'sppmix', maxnumcomp, data, xlims, ylims, L, LL, truncate, lamda, lamdab, hyper)
}

#' @export
DAMCMC2d_sppmix <- function(data, xlims, ylims, m, L, LL, truncate) {
    .Call('sppmix_DAMCMC2d_sppmix', PACKAGE = 'sppmix', data, xlims, ylims, m, L, LL, truncate)
}

#' @export
Factorial_sppmix <- function(x) {
    .Call('sppmix_Factorial_sppmix', PACKAGE = 'sppmix', x)
}

#' @export
invmat2d_sppmix <- function(A) {
    .Call('sppmix_invmat2d_sppmix', PACKAGE = 'sppmix', A)
}

#' @export
densNormMixatx_sppmix <- function(atx, mix) {
    .Call('sppmix_densNormMixatx_sppmix', PACKAGE = 'sppmix', atx, mix)
}

#' @export
densNormMix_atxy_sppmix <- function(atxy, mix) {
    .Call('sppmix_densNormMix_atxy_sppmix', PACKAGE = 'sppmix', atxy, mix)
}

#' @export
dNormMix_sppmix <- function(mix, x, y) {
    .Call('sppmix_dNormMix_sppmix', PACKAGE = 'sppmix', mix, x, y)
}

#' @export
Permute_vec_sppmix <- function(oldvec, perm) {
    .Call('sppmix_Permute_vec_sppmix', PACKAGE = 'sppmix', oldvec, perm)
}

#' @export
Permute_mat_sppmix <- function(oldmat, perm) {
    .Call('sppmix_Permute_mat_sppmix', PACKAGE = 'sppmix', oldmat, perm)
}

#' @export
GetAllPermutations_sppmix <- function(m) {
    .Call('sppmix_GetAllPermutations_sppmix', PACKAGE = 'sppmix', m)
}

#' @export
GetAPermutation_sppmix <- function(m, which) {
    .Call('sppmix_GetAPermutation_sppmix', PACKAGE = 'sppmix', m, which)
}

#' @export
GetGrid_sppmix <- function(len, xlims, ylims) {
    .Call('sppmix_GetGrid_sppmix', PACKAGE = 'sppmix', len, xlims, ylims)
}

#' @export
EqVec_sppmix <- function(v1, v2, tol) {
    .Call('sppmix_EqVec_sppmix', PACKAGE = 'sppmix', v1, v2, tol)
}

#' @export
logGammaFunc_sppmix <- function(x) {
    .Call('sppmix_logGammaFunc_sppmix', PACKAGE = 'sppmix', x)
}

#' @export
GammaFunc_sppmix <- function(x) {
    .Call('sppmix_GammaFunc_sppmix', PACKAGE = 'sppmix', x)
}

#' @export
dDirichlet_sppmix <- function(ps, ds) {
    .Call('sppmix_dDirichlet_sppmix', PACKAGE = 'sppmix', ps, ds)
}

#' @export
SumVec_sppmix <- function(v, start, end) {
    .Call('sppmix_SumVec_sppmix', PACKAGE = 'sppmix', v, start, end)
}

#' @export
SubstituteVec_sppmix <- function(v, subv, start) {
    .Call('sppmix_SubstituteVec_sppmix', PACKAGE = 'sppmix', v, subv, start)
}

#' @export
SubVec_sppmix <- function(v, start, end) {
    .Call('sppmix_SubVec_sppmix', PACKAGE = 'sppmix', v, start, end)
}

#' @export
GetMixtureMaxz_sppmix <- function(genmix, len, xlims, ylims) {
    .Call('sppmix_GetMixtureMaxz_sppmix', PACKAGE = 'sppmix', genmix, len, xlims, ylims)
}

#' @export
MakeMixtureList_sppmix <- function(gens_list, burnin) {
    .Call('sppmix_MakeMixtureList_sppmix', PACKAGE = 'sppmix', gens_list, burnin)
}

#' @export
GetStats_sppmix <- function(gens, alpha) {
    .Call('sppmix_GetStats_sppmix', PACKAGE = 'sppmix', gens, alpha)
}

#' @export
GetRealiz_ps_sppmix <- function(allgens, realiz) {
    .Call('sppmix_GetRealiz_ps_sppmix', PACKAGE = 'sppmix', allgens, realiz)
}

#' @export
GetRealiz_mus_sppmix <- function(allgens, realiz) {
    .Call('sppmix_GetRealiz_mus_sppmix', PACKAGE = 'sppmix', allgens, realiz)
}

#' @export
GetRealiz_sigmas_sppmix <- function(allgens, realiz) {
    .Call('sppmix_GetRealiz_sigmas_sppmix', PACKAGE = 'sppmix', allgens, realiz)
}

#' @export
PostGenGetBestPerm_sppmix <- function(allgens) {
    .Call('sppmix_PostGenGetBestPerm_sppmix', PACKAGE = 'sppmix', allgens)
}

#' @export
GetAllMeans_sppmix <- function(allgens, burnin) {
    .Call('sppmix_GetAllMeans_sppmix', PACKAGE = 'sppmix', allgens, burnin)
}

#' @export
GetCompDistr_sppmix <- function(numcomp, maxnumcomp) {
    .Call('sppmix_GetCompDistr_sppmix', PACKAGE = 'sppmix', numcomp, maxnumcomp)
}

#' @export
GetBDCompRealiz_sppmix <- function(genBDmix, genlamdas, numcomp, comp) {
    .Call('sppmix_GetBDCompRealiz_sppmix', PACKAGE = 'sppmix', genBDmix, genlamdas, numcomp, comp)
}

#' @export
GetAvgLabelsDiscrete2Multinomial_sppmix <- function(genzs, m) {
    .Call('sppmix_GetAvgLabelsDiscrete2Multinomial_sppmix', PACKAGE = 'sppmix', genzs, m)
}

#' @export
pmvnorm_mvtnorm <- function(lls, uls, mu, sigma) {
    .Call('sppmix_pmvnorm_mvtnorm', PACKAGE = 'sppmix', lls, uls, mu, sigma)
}

#' @export
rnorm2_sppmix <- function(n, mu, sigma) {
    .Call('sppmix_rnorm2_sppmix', PACKAGE = 'sppmix', n, mu, sigma)
}

#' @export
rWishart_sppmix <- function(df, A) {
    .Call('sppmix_rWishart_sppmix', PACKAGE = 'sppmix', df, A)
}

#' @export
rDiscrete_sppmix <- function(start, probs) {
    .Call('sppmix_rDiscrete_sppmix', PACKAGE = 'sppmix', start, probs)
}

rBinom_sppmix <- function(n, p) {
    .Call('sppmix_rBinom_sppmix', PACKAGE = 'sppmix', n, p)
}

rExp_sppmix <- function(a) {
    .Call('sppmix_rExp_sppmix', PACKAGE = 'sppmix', a)
}

#' @export
rDirichlet_sppmix <- function(d) {
    .Call('sppmix_rDirichlet_sppmix', PACKAGE = 'sppmix', d)
}

#' @export
rMultinomial_sppmix <- function(n, ps) {
    .Call('sppmix_rMultinomial_sppmix', PACKAGE = 'sppmix', n, ps)
}

#' @export
rNormMix_sppmix <- function(lamda, mix) {
    .Call('sppmix_rNormMix_sppmix', PACKAGE = 'sppmix', lamda, mix)
}

#' @export
rPerm_sppmix <- function(n) {
    .Call('sppmix_rPerm_sppmix', PACKAGE = 'sppmix', n)
}

