# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pbvnorm <- function(xlims, ylims, mu, sigma) {
    .Call('sppmix_pbvnorm', PACKAGE = 'sppmix', xlims, ylims, mu, sigma)
}

#' Approximate density of a normal mixture over a 2d domain.
#'
#' Approximate the density of each component in a normal mixture within the
#' domain using multivariate normal density function.
#'
#' @param mix An object of class \code{normmix}
#' @param xlim,ylim Vector of length two. Mixture density are estimated within
#' this range.
#' @importFrom mvtnorm dmvnorm
#'
#' @return A numerical vector corresponding to the density of each component
#'  within the window.
#' @export
approx_normmix <- function(mix, xlim, ylim) {
    .Call('sppmix_approx_normmix', PACKAGE = 'sppmix', mix, xlim, ylim)
}

