# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

invmat2d <- function(A) {
    .Call('sppmix_invmat2d', PACKAGE = 'sppmix', A)
}

rnorm2 <- function(n, mu, sigma) {
    .Call('sppmix_rnorm2', PACKAGE = 'sppmix', n, mu, sigma)
}

rDirichlet <- function(d) {
    .Call('sppmix_rDirichlet', PACKAGE = 'sppmix', d)
}

rWishart <- function(df, A) {
    .Call('sppmix_rWishart', PACKAGE = 'sppmix', df, A)
}

rBinom <- function(n, p) {
    .Call('sppmix_rBinom', PACKAGE = 'sppmix', n, p)
}

ApproxCompMass <- function(LL, ticsx, ticsy, areas, mu, sig, siginv) {
    .Call('sppmix_ApproxCompMass', PACKAGE = 'sppmix', LL, ticsx, ticsy, areas, mu, sig, siginv)
}

ApproxMHRatiomu <- function(LL, ticsx, ticsy, areas, curmu, propmu, sig, siginv) {
    .Call('sppmix_ApproxMHRatiomu', PACKAGE = 'sppmix', LL, ticsx, ticsy, areas, curmu, propmu, sig, siginv)
}

ApproxMHRatiosig <- function(LL, ticsx, ticsy, areas, mu1, propsigma, sig, siginv) {
    .Call('sppmix_ApproxMHRatiosig', PACKAGE = 'sppmix', LL, ticsx, ticsy, areas, mu1, propsigma, sig, siginv)
}

rMultinomial <- function(n, p) {
    .Call('sppmix_rMultinomial', PACKAGE = 'sppmix', n, p)
}

DAMCMC2d <- function(data, xlims, ylims, m, L, burnin, truncate) {
    .Call('sppmix_DAMCMC2d', PACKAGE = 'sppmix', data, xlims, ylims, m, L, burnin, truncate)
}

